name: Release

on:
  push:
    tags: ['v*']

jobs:
  release:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - run: scripts/build.cmd fd release

      - uses: softprops/action-gh-release@v2
        with:
          files: ./publish/CSharpHash.exe
